
--------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: ORACLE Version: 8

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'C:\Users\josep\Desktop\Other Shit\NEW SQL EAD\EAD_SQL_GENERATION.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE project_contacts CASCADE CONSTRAINTS;

DROP TABLE projectTeamMembers CASCADE CONSTRAINTS;

DROP TABLE project CASCADE CONSTRAINTS;

DROP TABLE client CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;

DROP TABLE contacts CASCADE CONSTRAINTS;

DROP TABLE projectActivities CASCADE CONSTRAINTS;

DROP TABLE payments CASCADE CONSTRAINTS;

DROP TABLE projectTeam_project CASCADE CONSTRAINTS;

DROP TABLE projectHours CASCADE CONSTRAINTS;

DROP TABLE roles CASCADE CONSTRAINTS;

DROP TABLE employeeRoles CASCADE CONSTRAINTS;

DROP TABLE projectArchive CASCADE CONSTRAINTS;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------
